require('./layout.css');
require('./footer/footer');
require('./header/header');
require('./nav/nav.css');
require('./nav-simple/nav-simple');
require('./nav-side/nav-side');
require('../banner/banner');
// require('../list/list');
var ff = require('../../PTools/ff');
var navSide = require('../../page/common/nav-side/nav-side');